version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASS:-password}
    volumes:
      - redis:/data
    networks:
      - internal
  app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    environment:
      APP_DATABASE__HOST: db
      APP_DATABASE__USER: postgres
      APP_DATABASE__PASSWORD: password
      APP_DATABASE__DATABASE_NAME: knowledge
      APP_REDIS_URI: "redis://redis:6379"
    networks:
      - internal
      - external

networks:
  internal:
    internal: true
  external:
    internal: false


volumes:
  db:
    driver: local
  redis:
    driver: local