version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: always
    expose:
      - '6379'
    command: redis-server
    volumes:
      - redis:/data
  app:
    build:
      context: .
      dockerfile: deployment/app/Dockerfile
    depends_on:
      - db
      - redis
    expose:
      - '8000'
    environment:
      APP_DATABASE__HOST: db
      APP_DATABASE__USER: postgres
      APP_DATABASE__PASSWORD: password
      APP_DATABASE__DATABASE_NAME: knowledge
      APP_REDIS_URI: "redis://redis:6379"
  startup:
    build:
      context: .
      dockerfile: deployment/startup/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/knowledge"
  nginx:
    build:
      context: deployment/nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: tbs.kldtz@gmail.com
    #env_file:
    #  - deployment/nginx/nginx-certbot.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt

volumes:
  db:
    driver: local
  redis:
    driver: local
  nginx_secrets: