version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: always
    expose:
      - '6379'
    command: redis-server
    volumes:
      - redis:/data
  app:
    build:
      context: .
      dockerfile: deployment/app/Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    environment:
      APP_DATABASE__HOST: db
      APP_DATABASE__USER: postgres
      APP_DATABASE__PASSWORD: password
      APP_DATABASE__DATABASE_NAME: knowledge
      APP_REDIS_URI: "redis://redis:6379"
  startup:
    build:
      context: .
      dockerfile: deployment/startup/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/knowledge"

volumes:
  db:
    driver: local
  redis:
    driver: local
  nginx_secrets: