application:
  port: 8000
  static_dir: "public"
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "knowledge"
redis_uri: "redis://localhost:6379"

